name: CI

on:
  push:
    paths:
      - "data/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "data/**"
      - ".github/workflows/**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            tools -> tools/target

      - name: Run CLI
        working-directory: tools
        run: cargo run --no-default-features ..